project = 'python-book'
copyright = '2020, Chi-Siang Feng'
author = 'Chi-Siang Feng'
release = '0.1'
extensions = []
templates_path = ['_templates']
master_doc = 'index'
language = 'zh-TW'
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']